services:
  backend:
    build: ./backend
    container_name: notoo-backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    container_name: notoo-frontend
    ports:
      - "8080:8080"
    restart: always
