version: "3.8"
services:
  backend:
    build: ./backend
    container_name: notoo-backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    container_name: notoo-frontend
    ports:
      - "3030:80"
    restart: always
