version: "3"

services:
  backend:
    build:
      context: ./backend
    container_name: notoo-backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: notoo-frontend
    ports:
      - "3030:3030"

  webhook:
    image: almir/webhook
    container_name: notoo-webhook
    ports:
      - "9000:9000"
    volumes:
      - ./deploy.sh:/etc/webhook/deploy.sh
      - ./webhook-config.json:/etc/webhook/hooks.json
    command: -hooks=/etc/webhook/hooks.json -verbose
