version: "3"

services:
  backend:
    build:
      context: ./backend
    container_name: notoo-backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: notoo-frontend
    ports:
      - "80:80"
