version: "3"

services:
  backend:
    build:
      context: ./backend
    container_name: notoo-backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: notoo-frontend
    ports:
      - "3030:80"
    restart: always

  webhook:
    image: almir/webhook
    container_name: notoo-webhook
    volumes:
      - ./webhook/hooks.json:/etc/webhook/hooks.json
      - ./deploy.sh:/scripts/deploy.sh
    command: -hooks /etc/webhook/hooks.json -port 9000 -verbose
    ports:
      - "9000:9000"
    restart: always
